FROM node:22-alpine

RUN apk add --no-cache \
    neovim \
    git \
    curl \
    bash \
    gcc \
    musl-dev \
    tmux \
    stow


WORKDIR /workspace

COPY package.json .

RUN npm install
RUN echo "alias ll='ls -la'" >> /root/.bashrc

CMD ["sh", "-c", "stow -d /root/dotfiles nvim tmux ghostty && npm run dev"]
