apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ino8ban4/my_portfolio/
    targetRevision: main
    path: platform-engineering/projects/express-api-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
