FROM node:22-alpine

RUN apk add --no-cache \
    neovim \
    git \
    curl \
    bash \
    gcc \
    musl-dev \
    tmux \
    stow \
    openssh


WORKDIR /workspace

COPY package.json .

RUN npm install
RUN echo "alias ll='ls -la'" >> /root/.bashrc

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]

