appName: express-api

replicaCount: 1

image:
  repository: ghcr.io/ino8ban4/express-api
  tag: sha-60e16f7
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

configMapName: express-config-dev
secretName: express-secret
