appName: express-api

replicaCount: 1

image:
  repository: express-api
  tag: v1
  pullPolicy: Never

service:
  type: NodePort
  port: 3000

configMapName: express-config-dev
secretName: express-secret
