FROM node:22-alpine

RUN apk add --no-cache \
    neovim \
    git \
    curl \
    bash \
    tmux \
    stow \
    openssh

WORKDIR /workspace

COPY package.json .

RUN npm install

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY scripts/setup-ssh.sh /scripts/setup-ssh.sh
RUN chmod +x /scripts/setup-ssh.sh

CMD ["/entrypoint.sh"]

