FROM node:22-alpine

RUN apk add --no-cache \
    git \
    curl \
    bash \
    tmux \
    stow \
    openssh

WORKDIR /workspace

COPY package.json .

RUN npm install

CMD ["tail", "-f", "/dev/null"]
